/**
 * Generates db/seed.json (and db/db.json) with fresh, relative dates so the
 * demo always feels current. Run: bun db/make-seed.ts
 */
import fs from "fs";
import path from "path";

const DAY = 24 * 60 * 60 * 1000;
const now = Date.now();
const daysAgo = (n: number) => new Date(now - n * DAY).toISOString();
const daysAhead = (n: number) => new Date(now + n * DAY).toISOString();
const dateOnly = (iso: string) => iso.slice(0, 10);

const seed = {
  users: [
    {
      id: "u_tobi",
      name: "Tobi A.",
      handle: "tobi-a",
      email: "tobi@deal.ng",
      phone: "+234 801 234 5678",
      whatsapp: "+2348012345678",
      channels: [
        { type: "whatsapp", value: "+2348012345678", primary: true },
        { type: "instagram", value: "@tobi.a.visuals" },
        { type: "email", value: "hello@tobiavisuals.ng" },
      ],
      password: "demo1234",
      craft: "Photographer",
      location: "Akure, Ondo State",
      bio: "Story-driven photography for brands, weddings and people. 6 years behind the lens, 200+ happy clients across Nigeria.",
      verified: true,
      onboarded: true,
      createdAt: daysAgo(220),
    },
  ],
  services: [
    {
      id: "sv_prewedding",
      userId: "u_tobi",
      title: "Pre-wedding Photography",
      desc: "A relaxed couple's session that tells your story — location scouting, styling guide and a same-week gallery.",
      from: 120000,
      duration: "Half day",
      popular: true,
      includes: ["2 outfit changes", "40+ edited photos", "Private online gallery", "Print release"],
    },
    {
      id: "sv_portrait",
      userId: "u_tobi",
      title: "Portrait Session",
      desc: "Clean studio or outdoor portraits for personal brands, LinkedIn and family keepsakes.",
      from: 50000,
      duration: "2 hours",
      popular: false,
      includes: ["1 outfit change", "15 edited photos", "Web + print sizes"],
    },
    {
      id: "sv_event",
      userId: "u_tobi",
      title: "Event Photography",
      desc: "Full coverage of your event — arrivals to the last dance, delivered in a shareable gallery.",
      from: 150000,
      duration: "Full day",
      popular: false,
      includes: ["Up to 8 hours coverage", "150+ edited photos", "48-hour highlight set", "Private online gallery"],
    },
    {
      id: "sv_video",
      userId: "u_tobi",
      title: "Short Video Coverage",
      desc: "A 60–90 second cinematic recap of your event or brand day, vertical and landscape cuts.",
      from: 80000,
      duration: "Half day",
      popular: false,
      includes: ["Cinematic edit", "Vertical + 16:9 cuts", "Licensed music", "3 revision rounds"],
    },
  ],
  requests: [
    {
      id: "r_lola",
      ref: "REQ-2025-00021",
      creatorId: "u_tobi",
      serviceId: "sv_prewedding",
      clientName: "Lola Adeyemi",
      clientContact: "+234 802 555 1212",
      eventDate: dateOnly(daysAhead(35)),
      location: "Ikoyi, Lagos",
      budgetMin: 100000,
      budgetMax: 150000,
      description:
        "We got engaged in December and want a pre-wedding session that feels like us — warm, playful, maybe Lekki conservation centre at golden hour.",
      notes: "Fiance is camera-shy, so a relaxed vibe is key.",
      status: "new",
      createdAt: daysAgo(2),
    },
    {
      id: "r_tech",
      ref: "REQ-2025-00022",
      creatorId: "u_tobi",
      serviceId: "sv_event",
      clientName: "TechConnect Africa",
      clientContact: "events@techconnect.africa",
      eventDate: dateOnly(daysAhead(21)),
      location: "Landmark Centre, Victoria Island",
      budgetMin: 120000,
      budgetMax: 200000,
      description:
        "Annual tech summit — about 300 guests. We need arrivals, panel sessions, networking and the after-party covered, plus a quick highlight set for press.",
      notes: "Press team needs 10 photos within 24 hours.",
      status: "new",
      createdAt: daysAgo(1),
    },
    {
      id: "r_glow",
      ref: "REQ-2025-00020",
      creatorId: "u_tobi",
      serviceId: "sv_portrait",
      clientName: "Glow Skincare",
      clientContact: "+234 809 444 2020",
      eventDate: dateOnly(daysAhead(14)),
      location: "Lekki Phase 1, Lagos",
      budgetMin: 50000,
      budgetMax: 90000,
      description: "Founder portraits + team headshots for our new website launch.",
      notes: "",
      status: "replied",
      createdAt: daysAgo(6),
    },
  ],
  deals: [
    {
      id: "d_deal001",
      ref: "DEAL-001",
      creatorId: "u_tobi",
      requestId: "r_lola",
      shareToken: "tok_lola001",
      title: "Lola & Tunde Pre-wedding Shoot",
      serviceTitle: "Pre-wedding Photography",
      client: { name: "Lola Adeyemi", contact: "+234 802 555 1212" },
      summary:
        "Golden-hour couple session at Lekki Conservation Centre with 2 outfit changes and a same-week private gallery.",
      eventDate: dateOnly(daysAhead(35)),
      location: "Lekki Conservation Centre, Lagos",
      message:
        "Hi Lola! Thank you for reaching out on DEAL. Here is the full plan for your pre-wedding session — deposit is all I need to lock the date.",
      scope:
        "Pre-shoot styling call, location scouting, 4-hour golden-hour session, 2 outfit changes, same-week gallery delivery.",
      deliverables: [
        "40+ edited high-resolution photos",
        "Private online gallery (12 months)",
        "Web + print size exports",
        "Print release letter",
      ],
      price: 120000,
      depositPercent: 50,
      installmentsCount: 2,
      startDate: dateOnly(daysAhead(33)),
      dueDate: dateOnly(daysAhead(39)),
      revisions: 2,
      status: "active",
      events: [
        { at: daysAgo(7), type: "created", label: "Deal created from Lola's request", actor: "creator" },
        { at: daysAgo(7), type: "sent", label: "Deal sent to Lola Adeyemi", actor: "creator" },
        { at: daysAgo(6), type: "accepted", label: "Deal accepted", actor: "client" },
        {
          at: daysAgo(6),
          type: "deposit_paid",
          label: "Deposit paid — ₦60,000 secured in Payaza escrow (ref PZ-8KD92MAQ)",
          actor: "client",
        },
        {
          at: daysAgo(2),
          type: "balance_paid",
          label: "Installment 1 of 2 paid — ₦30,000 secured in Payaza escrow (ref PZ-3FJ81XWP)",
          actor: "client",
        },
      ],
      payments: [
        {
          id: "p_lola_dep",
          type: "deposit",
          label: "Deposit (50%)",
          amount: 60000,
          method: "card",
          methodLabel: "Card payment",
          provider: "payaza",
          reference: "PZ-8KD92MAQ",
          status: "held",
          paidAt: daysAgo(6),
        },
        {
          id: "p_lola_inst1",
          type: "installment",
          label: "Installment 1 of 2",
          amount: 30000,
          method: "transfer",
          methodLabel: "Bank transfer",
          provider: "payaza",
          reference: "PZ-3FJ81XWP",
          status: "held",
          paidAt: daysAgo(2),
        },
      ],
      deliveries: [],
      finalFiles: [],
      createdAt: daysAgo(7),
      sentAt: daysAgo(7),
      acceptedAt: daysAgo(6),
      depositPaidAt: daysAgo(6),
    },
    {
      id: "d_deal002",
      ref: "DEAL-002",
      creatorId: "u_tobi",
      requestId: null,
      shareToken: "tok_glow002",
      title: "Glow Skincare Brand Portraits",
      serviceTitle: "Portrait Session",
      client: { name: "Amara Okafor", contact: "+234 809 444 2020" },
      summary:
        "Founder portraits and product-in-hand shots for Glow Skincare's website relaunch, studio session.",
      eventDate: dateOnly(daysAhead(14)),
      location: "Studio 9, Lekki Phase 1, Lagos",
      message:
        "Hi Amara, lovely speaking with you. This covers the founder portraits and team headshots we discussed — accept and pay the deposit to lock the studio date.",
      scope:
        "Studio session (3 hours), 2 backdrop looks, founder portraits + 4 team headshots, retouching included.",
      deliverables: [
        "25+ edited portraits",
        "Web-optimised exports for the site",
        "1 retried look on request",
        "Commercial usage licence (12 months)",
      ],
      price: 60000,
      depositPercent: 50,
      installmentsCount: 2,
      startDate: dateOnly(daysAhead(14)),
      dueDate: dateOnly(daysAhead(18)),
      revisions: 2,
      status: "sent",
      events: [
        { at: daysAgo(1), type: "created", label: "Deal created for Glow Skincare", actor: "creator" },
        { at: daysAgo(1), type: "sent", label: "Deal sent to Amara Okafor", actor: "creator" },
      ],
      payments: [],
      deliveries: [],
      finalFiles: [],
      createdAt: daysAgo(1),
      sentAt: daysAgo(1),
    },
    {
      id: "d_deal003",
      ref: "DEAL-003",
      creatorId: "u_tobi",
      requestId: "r_tech",
      shareToken: "tok_tech003",
      title: "TechConnect Summit Coverage",
      serviceTitle: "Event Photography",
      client: { name: "TechConnect Africa", contact: "events@techconnect.africa" },
      summary:
        "Full-day coverage of the annual summit at Landmark Centre — 300 guests, panels, networking and after-party.",
      eventDate: dateOnly(daysAhead(21)),
      location: "Landmark Centre, Victoria Island, Lagos",
      message:
        "Hello! Here's the coverage plan for TechConnect Summit. Everything you approved is inside — the 24-hour press set is included.",
      scope:
        "8 hours on-site coverage, 2 photographers' shot list, 48-hour highlight set, press-priority edits within 24 hours.",
      deliverables: [
        "150+ edited photos",
        "10-photo press set within 24 hours",
        "48-hour highlight gallery",
        "Full private gallery (12 months)",
      ],
      price: 150000,
      depositPercent: 50,
      installmentsCount: 2,
      startDate: dateOnly(daysAhead(21)),
      dueDate: dateOnly(daysAhead(26)),
      revisions: 2,
      status: "delivered",
      events: [
        { at: daysAgo(9), type: "created", label: "Deal created from TechConnect's request", actor: "creator" },
        { at: daysAgo(9), type: "sent", label: "Deal sent to TechConnect Africa", actor: "creator" },
        { at: daysAgo(8), type: "accepted", label: "Deal accepted", actor: "client" },
        {
          at: daysAgo(8),
          type: "deposit_paid",
          label: "Deposit paid — ₦75,000 secured in Payaza escrow (ref PZ-9QM41NTV)",
          actor: "client",
        },
        { at: daysAgo(1), type: "delivered", label: "Delivery submitted for review", actor: "creator" },
      ],
      payments: [
        {
          id: "p_tech_dep",
          type: "deposit",
          label: "Deposit (50%)",
          amount: 75000,
          method: "ussd",
          methodLabel: "USSD payment",
          provider: "payaza",
          reference: "PZ-9QM41NTV",
          status: "held",
          paidAt: daysAgo(8),
        },
      ],
      deliveries: [
        {
          id: "dl_tech1",
          note: "Highlight gallery for your review — 60 selects from the summit. Press set is included. Final full gallery follows after approval.",
          files: [
            { id: "f_tech1", name: "TechConnect-summit-highlights.zip", size: "212.4 MB", kind: "ZIP" },
            { id: "f_tech2", name: "Press-set (24hr).zip", size: "48.1 MB", kind: "ZIP" },
          ],
          submittedAt: daysAgo(1),
        },
      ],
      finalFiles: [],
      createdAt: daysAgo(9),
      sentAt: daysAgo(9),
      acceptedAt: daysAgo(8),
      depositPaidAt: daysAgo(8),
      deliveredAt: daysAgo(1),
    },
    {
      id: "d_deal004",
      ref: "DEAL-004",
      creatorId: "u_tobi",
      requestId: null,
      shareToken: "tok_ezek004",
      title: "Ezekiel Studio Session",
      serviceTitle: "Portrait Session",
      client: { name: "Ezekiel Danjuma", contact: "+234 803 777 9090" },
      summary: "Personal-brand studio portraits for Ezekiel's coaching business relaunch.",
      eventDate: dateOnly(daysAhead(3)),
      location: "Studio 9, Lekki Phase 1, Lagos",
      message: "Brother Ezekiel — here's our agreed plan. Paid in full upfront, so once you approve the work everything releases automatically.",
      scope: "Studio session (2 hours), 1 backdrop look, 15 edited portraits, retouching included.",
      deliverables: ["15 edited portraits", "Web + print sizes", "Personal usage licence"],
      price: 120000,
      depositPercent: 100,
      installmentsCount: 0,
      startDate: dateOnly(daysAhead(3)),
      dueDate: dateOnly(daysAhead(5)),
      revisions: 1,
      status: "approved",
      events: [
        { at: daysAgo(12), type: "created", label: "Deal created for Ezekiel Danjuma", actor: "creator" },
        { at: daysAgo(12), type: "sent", label: "Deal sent to Ezekiel Danjuma", actor: "creator" },
        { at: daysAgo(11), type: "accepted", label: "Deal accepted", actor: "client" },
        {
          at: daysAgo(11),
          type: "deposit_paid",
          label: "Full payment paid — ₦120,000 secured in Payaza escrow (ref PZ-77AXQ2LM)",
          actor: "client",
        },
        { at: daysAgo(4), type: "delivered", label: "Delivery submitted for review", actor: "creator" },
        { at: daysAgo(3), type: "approved", label: "Work approved by client — completed", actor: "client" },
        {
          at: daysAgo(3),
          type: "payment_released",
          label: "₦120,000 released from escrow to the creator's Payaza payout account",
          actor: "system",
        },
      ],
      payments: [
        {
          id: "p_ez_full",
          type: "deposit",
          label: "Full payment",
          amount: 120000,
          method: "card",
          methodLabel: "Card payment",
          provider: "payaza",
          reference: "PZ-77AXQ2LM",
          status: "released",
          paidAt: daysAgo(11),
          releasedAt: daysAgo(3),
        },
      ],
      deliveries: [
        {
          id: "dl_ez1",
          note: "Watermarked selects for your review — pick any tweaks and approve when happy.",
          files: [
            { id: "f_ez1", name: "Ezekiel-selects.zip", size: "96.2 MB", kind: "ZIP" },
          ],
          submittedAt: daysAgo(4),
        },
      ],
      finalFiles: [],
      createdAt: daysAgo(12),
      sentAt: daysAgo(12),
      acceptedAt: daysAgo(11),
      depositPaidAt: daysAgo(11),
      deliveredAt: daysAgo(4),
      approvedAt: daysAgo(3),
      paymentReleasedAt: daysAgo(3),
    },
    {
      id: "d_deal005",
      ref: "DEAL-005",
      creatorId: "u_tobi",
      requestId: null,
      shareToken: "tok_lekki005",
      title: "Lekki Property Shoot",
      serviceTitle: "Short Video Coverage",
      client: { name: "Chidi Bello", contact: "+234 805 222 3344" },
      summary: "Cinematic walkthrough video of a 4-bedroom terrace for a realtor's listing.",
      eventDate: dateOnly(daysAhead(-16)),
      location: "Chevron Drive, Lekki, Lagos",
      message: "Mr Chidi — full plan for the walkthrough video as agreed. It was a pleasure.",
      scope: "On-site cinematic walkthrough (3 hours), drone shots, licensed music, vertical + landscape cuts.",
      deliverables: ["60–90s cinematic walkthrough", "Vertical cut for Instagram", "Landscape cut for YouTube", "10 photo stills"],
      price: 80000,
      depositPercent: 50,
      installmentsCount: 1,
      startDate: dateOnly(daysAhead(-16)),
      dueDate: dateOnly(daysAhead(-11)),
      revisions: 2,
      status: "completed",
      events: [
        { at: daysAgo(24), type: "created", label: "Deal created for Chidi Bello", actor: "creator" },
        { at: daysAgo(24), type: "sent", label: "Deal sent to Chidi Bello", actor: "creator" },
        { at: daysAgo(23), type: "accepted", label: "Deal accepted", actor: "client" },
        {
          at: daysAgo(23),
          type: "deposit_paid",
          label: "Deposit paid — ₦40,000 secured in Payaza escrow (ref PZ-5HTR29KD)",
          actor: "client",
        },
        { at: daysAgo(16), type: "delivered", label: "Delivery submitted for review", actor: "creator" },
        { at: daysAgo(12), type: "changes_requested", label: "Revision requested: “Make the opening drone shot slower”", actor: "client" },
        { at: daysAgo(10), type: "delivered", label: "Revised delivery submitted", actor: "creator" },
        { at: daysAgo(9), type: "approved", label: "Work approved by client — completed", actor: "client" },
        {
          at: daysAgo(9),
          type: "payment_released",
          label: "₦40,000 released from escrow to the creator's Payaza payout account",
          actor: "system",
        },
        {
          at: daysAgo(8),
          type: "balance_paid",
          label: "Balance installment paid — ₦40,000 received by creator (work already approved, ref PZ-1WYB64FS)",
          actor: "client",
        },
        { at: daysAgo(7), type: "files_released", label: "Final files released to client", actor: "creator" },
        { at: daysAgo(6), type: "completed", label: "Client downloaded final files and left a 5-star review", actor: "client" },
      ],
      payments: [
        {
          id: "p_lekki_dep",
          type: "deposit",
          label: "Deposit (50%)",
          amount: 40000,
          method: "card",
          methodLabel: "Card payment",
          provider: "payaza",
          reference: "PZ-5HTR29KD",
          status: "released",
          paidAt: daysAgo(23),
          releasedAt: daysAgo(9),
        },
        {
          id: "p_lekki_bal",
          type: "installment",
          label: "Balance installment",
          amount: 40000,
          method: "transfer",
          methodLabel: "Bank transfer",
          provider: "payaza",
          reference: "PZ-1WYB64FS",
          status: "released",
          paidAt: daysAgo(8),
          releasedAt: daysAgo(8),
        },
      ],
      deliveries: [
        {
          id: "dl_lekki1",
          note: "First cut of the walkthrough — review and let me know any tweaks.",
          files: [{ id: "f_lk1", name: "Lekki-walkthrough-v1.mp4", size: "184.7 MB", kind: "MP4" }],
          submittedAt: daysAgo(16),
        },
        {
          id: "dl_lekki2",
          note: "Slower opening drone shot as requested — ready for your approval.",
          files: [{ id: "f_lk2", name: "Lekki-walkthrough-v2.mp4", size: "186.1 MB", kind: "MP4" }],
          submittedAt: daysAgo(10),
        },
      ],
      finalFiles: [
        { id: "f_lk3", name: "Lekki-walkthrough-FINAL-16x9.mp4", size: "188.3 MB", kind: "MP4" },
        { id: "f_lk4", name: "Lekki-walkthrough-FINAL-9x16.mp4", size: "97.6 MB", kind: "MP4" },
        { id: "f_lk5", name: "Photo-stills.zip", size: "62.9 MB", kind: "ZIP" },
      ],
      createdAt: daysAgo(24),
      sentAt: daysAgo(24),
      acceptedAt: daysAgo(23),
      depositPaidAt: daysAgo(23),
      deliveredAt: daysAgo(10),
      approvedAt: daysAgo(9),
      paymentReleasedAt: daysAgo(9),
      balancePaidAt: daysAgo(8),
      filesReleasedAt: daysAgo(7),
      completedAt: daysAgo(6),
    },
  ],
  bookings: [
    {
      id: "bk_001",
      ref: "BKG-001",
      creatorId: "u_tobi",
      serviceId: "sv_portrait",
      sessionType: "Portrait Session",
      clientName: "Lola Adeyemi",
      clientContact: "+234 802 555 1212",
      date: dateOnly(daysAhead(3)),
      time: "11:00",
      note: "Want to visit the studio and talk through our pre-wedding shoot ideas before we book the date.",
      status: "requested",
      createdAt: daysAgo(1),
    },
    {
      id: "bk_002",
      ref: "BKG-002",
      creatorId: "u_tobi",
      serviceId: "sv_event",
      sessionType: "Event Photography",
      clientName: "TechConnect Africa",
      clientContact: "events@techconnect.africa",
      date: dateOnly(daysAhead(6)),
      time: "09:00",
      note: "Venue walkthrough at Landmark Centre to plan the summit shot list.",
      status: "confirmed",
      createdAt: daysAgo(3),
    },
    {
      id: "bk_003",
      ref: "BKG-003",
      creatorId: "u_tobi",
      serviceId: "sv_portrait",
      sessionType: "General consultation",
      clientName: "Glow Skincare",
      clientContact: "+234 809 444 2020",
      date: dateOnly(daysAhead(-6)),
      time: "14:00",
      note: "Brand planning call ahead of the website relaunch shoot.",
      status: "completed",
      createdAt: daysAgo(9),
    },
  ],
  settings: {
    earningsSeries: [
      { month: "Aug", amount: 320000 },
      { month: "Sep", amount: 410000 },
      { month: "Oct", amount: 365000 },
      { month: "Nov", amount: 440000 },
      { month: "Dec", amount: 485000 },
      { month: "Jan", amount: 460000 },
    ],
  },
};

const outDir = path.join(process.cwd(), "db");
fs.writeFileSync(path.join(outDir, "seed.json"), JSON.stringify(seed, null, 2));
fs.writeFileSync(path.join(outDir, "db.json"), JSON.stringify(seed, null, 2));
console.log("Seed written: db/seed.json + db/db.json");
console.log("Deals:", seed.deals.length, "| Bookings:", seed.bookings.length);
